### ISSUE TITLE
Last param of wp_register_style() should be a string

### ISSUE THREAD

**Issue by prichey** [40Digits/wordpress-starter-theme#1]
On a fresh install I'm getting the following: 

`Notice: Use of undefined constant all - assumed 'all' in /var/www/vhosts/faultless/wp-content/themes/faultless/functions/wordpress/enqueue_scripts.php on line 6`.

The line in question (`wp_register_style('style.css', (get_stylesheet_directory_uri() . '/style.css'), false, false, all);`) should be 
`wp_register_style('style.css', (get_stylesheet_directory_uri() . '/style.css'), false, false, 'all');`. 

The last param should be the string `'all'`.

**Comment by ckhicks** [comment]
Fixed! Good catch.
