### ISSUE TITLE
Implement as a scaffolding recipe for something like Yeoman

### ISSUE THREAD

**Issue by chuckmo** [40Digits/wordpress-starter-theme#2]
Simplify the new project process.

**Comment by besimhu** [comment]
Didn't have a chance to comment as I was on vacation. 

I wouldn't mind something like this as a feature enhancement for down the road.

**Comment by ckhicks** [comment]
We talked about this in Open Source Committee on Friday. The general consensus was that we aren't opposed to something like this, but we don't have a need to develop it from our end. If someone wanted to take the reigns and build out this functionality, we would likely be able to include it into a future release.

**Comment by hahnzilla** [comment]
@chuckmo You should check out [YeoPress](https://github.com/wesleytodd/YeoPress). It appears to be "The officially un-official Yeoman Generator for WordPress"

**Comment by besimhu** [comment]
I'm all for feature enhancement, as long as it's separate to what we already have. 

Not everyone will find it as usable/useful and I'd rather not go down the HelperPress customization path. I'd also like to keep the boilerplate as what it is, a boilerplate that can be easily used between projects.

**Comment by chuckmo** [comment]
The main part I'm interested in is the gulp starter, so that's what should
be Yeo'd.

On Wednesday, May 6, 2015, Besim Huskic notifications@github.com wrote:

> I'm all for feature enhancement, as long as it's separate to what we
> already have.
> 
> Not everyone will find it as usable/useful and I'd would rather not go
> down the HelperPress customization path. I'd also like to keep the
> boilerplate as what it is, a boilerplate that can be easily used between
> projects.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/40Digits/wordpress-starter-theme/issues/2#issuecomment-99573740
> .

## 

Sent from Gmail Mobile

**Comment by ghost** [comment]
We have adopted 40dev-tools which acts as our project scaffolder! Thus, i'm going to go ahead and close this issue.
