### ISSUE TITLE
Make CPT example something less confusing

### ISSUE THREAD

**Issue by prichey** [40Digits/wordpress-starter-theme#4]
I can totally do a PR for this, I just wanted to create an issue first to see if anybody had thoughts. IMO 'Portfolio' is not a great example CPT because the distinction between general name / plural being 'Portfolio' and the singular name being 'Portfolio Item' is confusing. I think it'd be much more clear with something that follows more conventional pluralization, like Digit / Digits, etc.

**Comment by besimhu** [comment]
I've been looking into minimizing the amount of labels needed on the setup. Here's an example below of what's all needed really. 

```
'labels' => array(
    'name' => __( 'Products' ),
    'singular_name' => __( 'Product' )
),
```

**Comment by prichey** [comment]
I'm all for reducing the amount of effort in setting up a CPT, and maybe that can / should be a separate issue, I just think it should be something other than Portfolio. 

Also, the rewrite array in the args is `'rewrite' => array('slug' => 'project'),` which doesn't even match Portfolio.

**Comment by prichey** [comment]
And then maybe in the `supports` array we could list everything that it can possibly be, since that could potentially save a trip to the docs.

**Comment by besimhu** [comment]
In regards to the rewrite slug, and why use `project` as a slug.

Our custom post type is Portfolio & that's what we are registering it as also `register_post_type('portfolio', $args);`. However, there are instances when we want to rewrite the slug to be something else, in this case the examples was `'rewrite' => array('slug' => 'project')`. It could have been `'rewrite' => array('slug' => 'portfolio/project')` too. 

So yeah, I can see how you may be confused by it, but at the same time it too makes sense as we are showing only a project. 

In either case, I will change it to `'rewrite' => array('slug' => 'custom-slug')`

**Comment by prichey** [comment]
Yeah, that makes a lot more sense to me. :+1:

**Comment by ghost** [comment]
Edited the CPT example to use Movies instead of Portfolio to be more explicit.
